config/routes.rb
Rails.application.routes.draw do
  resources :client_data_entries do
    member do
      get 'sub_form', to: "client_data_entries#sub_form"
    end
    member do
      get 'sub_form_list', to: "client_data_entries#sub_form_list"
    end
  end
  resources :client_legal_forms do
    collection do
      get :download_csv
    end
    member do
      get '/new_for_client/', to: "client_legal_forms#new_for_client"
    end
    member do
      get '/forms_by_client/', to: "client_legal_forms#forms_by_client"
    end
  end
  get '/subForm/:id', to: 'client_data_entries#subForm'
  get '/myForm/:id', to: 'client_legal_forms#userEdit'
  get '/hashError', to: 'home#bad_hash'
  get '/clientSuccess', to: 'home#client_success'
  get '/downloadCsv/:id', to: 'client_answers#download_csv'
  resources :clients
  resources :legal_form_questions
  resources :legal_forms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/legal_forms_controller.rb
class LegalFormsController < ApplicationController
  before_action :set_legal_form, only: %i[ show edit update destroy ]

  # GET /legal_forms or /legal_forms.json
  def index
    @legal_forms = LegalForm.all
  end

  # GET /legal_forms/1 or /legal_forms/1.json
  def show
    @questions = LegalForm.find(params[:id]).legal_form_questions.all
  end

  # GET /legal_forms/new
  def new
    @legal_form = LegalForm.new
  end

  # GET /legal_forms/1/edit
  def edit
  end

  # POST /legal_forms or /legal_forms.json
  def create
    @legal_form = LegalForm.new(legal_form_params)

    respond_to do |format|
      if @legal_form.save
        format.html { redirect_to legal_form_url(@legal_form), notice: "Legal form was successfully created." }
        format.json { render :show, status: :created, location: @legal_form }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @legal_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /legal_forms/1 or /legal_forms/1.json
  def update
    respond_to do |format|
      if @legal_form.update(legal_form_params)
        format.html { redirect_to legal_form_url(@legal_form), notice: "Legal form was successfully updated." }
        format.json { render :show, status: :ok, location: @legal_form }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @legal_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /legal_forms/1 or /legal_forms/1.json
  def destroy
    @legal_form.destroy!

    respond_to do |format|
      format.html { redirect_to legal_forms_url, notice: "Legal form was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_legal_form
      @legal_form = LegalForm.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def legal_form_params
      params.require(:legal_form).permit(:name)
    end
end

app/helpers/legal_forms_helper.rb
module LegalFormsHelper
end

app/views/legal_forms/_form.html.erb
<%= form_with(model: legal_form) do |form| %>
  <% if legal_form.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(legal_form.errors.count, "error") %> prohibited this legal_form from being saved:</h2>

      <ul>
        <% legal_form.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label "Subform", style: "display: block" %>
    <%= form.check_box :isSubform %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/legal_forms/_legal_form.html.erb
<div id="<%= dom_id legal_form %>">
  <p>
    <strong>Name:</strong>
    <%= legal_form.name %>
  </p>
  <% @questions.each do  |question| %>
    <div>
      <%=question.position %>) <%=question.question %>
    </div>
  <% end %>


</div>

app/views/legal_forms/_legal_form_list.html.erb
<div id="<%= dom_id legal_form %>">
  <p>
    <strong>Name:</strong>
    <%= legal_form.name %>
  </p>
  <% legal_form.legal_form_questions.where(legal_form_id: legal_form.id).each do  |question| %>
    <div>
      <%=question.position %>) <%=question.question %>
    </div>
  <% end %>
</div>

app/views/legal_forms/edit.html.erb
<h1>Editing legal form</h1>

<%= render "form", legal_form: @legal_form %>

<br>

<div>
  <%= link_to "Show this legal form", @legal_form %> |
  <%= link_to "Back to legal forms", legal_forms_path %>
</div>

app/views/legal_forms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Legal forms</h1>

<div id="legal_forms">
  <% @legal_forms.each do |legal_form| %>
    <p><%= legal_form.name %> <%= "(Subform)" if legal_form.isSubform  %>: <%= link_to "Show this legal form", legal_form %></p>

  <% end %>
</div>

<%= link_to "New legal form", new_legal_form_path %>

app/views/legal_forms/new.html.erb
<h1>New legal form</h1>

<%= render "form", legal_form: @legal_form %>

<br>

<div>
  <%= link_to "Back to legal forms", legal_forms_path %>
</div>

app/views/legal_forms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @legal_form %><%=@testVar%>

<div>
  <%= link_to "Edit this legal form", edit_legal_form_path(@legal_form) %> |
  <%= link_to "Back to legal forms", legal_forms_path %>

  <%= button_to "Destroy this legal form", @legal_form, method: :delete %>
</div>