config/routes.rb
Rails.application.routes.draw do
  resources :client_data_entries do
    member do
      get 'sub_form', to: "client_data_entries#sub_form"
    end
    member do
      get 'sub_form_list', to: "client_data_entries#sub_form_list"
    end
  end
  resources :client_legal_forms do
    collection do
      get :download_csv
    end
    member do
      get '/new_for_client/', to: "client_legal_forms#new_for_client"
    end
    member do
      get '/forms_by_client/', to: "client_legal_forms#forms_by_client"
    end
  end
  get '/subForm/:id', to: 'client_data_entries#subForm'
  get '/myForm/:id', to: 'client_legal_forms#userEdit'
  get '/hashError', to: 'home#bad_hash'
  get '/clientSuccess', to: 'home#client_success'
  get '/downloadCsv/:id', to: 'client_answers#download_csv'
  resources :clients
  resources :legal_form_questions
  resources :legal_forms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/client_legal_forms_controller.rb
require 'csv'

class ClientLegalFormsController < ApplicationController
  before_action :set_client_legal_form, only: %i[ show edit update destroy ]

  # GET /client_legal_forms or /client_legal_forms.json
  def index
    @client_legal_forms = ClientLegalForm.where(subFormQuestion_id: nil)
  end

  # GET /client_legal_forms/1 or /client_legal_forms/1.json
  def show
    client_legal_form = ClientLegalForm.find(params[:id])
    @answers = ClientAnswer.where(client_legal_form_id: params[:id])
    @client_legal_form_id = params[:id]
  end

  # GET /client_legal_forms/new
  def new
    @client_dropdown = Client.all.map { |client| [client.first_name, client.id] }
    init_new_client_legal_form
  end

  def new_for_client
    @client = Client.find(params[:id])
    init_new_client_legal_form
  end

  def forms_by_client
    @client = Client.find(params[:id])
    @client_legal_forms = ClientLegalForm.where(client_id: params[:id], subFormQuestion_id: nil)
  end

  def sub_form
    @test= "mytest"
  end

  # GET /client_legal_forms/1/edit
  def edit
  end

  # POST /client_legal_forms or /client_legal_forms.json
  def create
    @client_legal_form = ClientLegalForm.new(client_legal_form_params)

    form_hash = generateHash
    @client_legal_form.form_hash = form_hash


    legal_form_questions = LegalFormQuestion.where(legal_form_id: client_legal_form_params['legal_form_id'])
    respond_to do |format|
      if @client_legal_form.save
        legal_form_questions.each do |legal_form|
          client_answer = ClientAnswer.new({:question => legal_form.question,
                                            :position => legal_form.position,
                                            :options => legal_form.options,
                                            :question_type => legal_form.question_type,
                                            :client_legal_form_id => @client_legal_form.id
                                           })
          puts "new client answer"
          puts client_answer
          if client_answer.save
            puts "client answer saved"
          else
            puts "client answer not saved"
            puts client_answer.errors
          end
        end

        if client_legal_form_params[:subFormQuestion_id]
          format.html {redirect_to "/client_data_entries/#{@client_legal_form.id}/sub_form"}
        else
          format.html { redirect_to client_legal_forms_path, notice: "Client legal form was successfully created." }
        end
        format.json { render :show, status: :created, location: @client_legal_form }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client_legal_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /client_legal_forms/1 or /client_legal_forms/1.json
  def update
    respond_to do |format|
      if @client_legal_form.update(client_legal_form_params)
        format.html { redirect_to client_legal_form_url(@client_legal_form), notice: "Client legal form was successfully updated." }
        format.json { render :show, status: :ok, location: @client_legal_form }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client_legal_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /client_legal_forms/1 or /client_legal_forms/1.json
  def destroy
    @client_legal_form.destroy!
    unless params[:stimulus]
      respond_to do |format|
        format.html { redirect_to client_legal_forms_url, notice: "Client legal form was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end

  def download_csv
    respond_to do |format|
      @ClientAnswer = ClientAnswer.where(client_legal_form_id: params[:formID])
      @ClientLegalForm = ClientLegalForm.find(params[:formID])
      format.csv { send_data generate_csv(@ClientAnswer), filename: "completed_form-#{@ClientLegalForm.most_recent_login.strftime("%Y-%m-%d_%H-%M")}.csv" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client_legal_form
      @client_legal_form = ClientLegalForm.find(params[:id])
    end

    def init_new_client_legal_form
      @client_legal_form = ClientLegalForm.new
      @legal_form_dropdown = LegalForm.where(isSubform: false).map { |legal_form| [legal_form.name, legal_form.id] }
    end

    # Only allow a list of trusted parameters through.
    def client_legal_form_params
      params.require(:client_legal_form).permit(:client_id, :legal_form_id, :first_login_date, :most_recent_login, :form_hash, :subFormQuestion_id, :stimulus)
    end

    def generateHash
      @random_string = SecureRandom.alphanumeric(36)
      if ClientLegalForm.where(:form_hash => @random_string).count > 0
        @random_string = generateHash
      end
      @random_string
    end

  def view_subforms(id)
    # subforms = ClientLegalForm.where(subFormQuestion_id: id)
    "test"
  end

  def generate_csv(client_answers)
    CSV.generate(headers: true) do |csv|
      csv << ["Question", "Answer"] # Add your desired headers
      client_answers.each do |client_answer|
        if client_answer.question_type == "SubForm"
          puts "subfrom form outer"
          subforms = client_answer.get_subform
          subforms.each do |subform|
            puts 'subform data'
            subform.client_answers.each do |subform_answers|
              puts 'subform answers'
              csv << [subform_answers.question, subform_answers.answer] # Add your desired fields
            end
          end
        else
          csv << [client_answer.question, client_answer.answer] # Add your desired fields
        end
      end
    end
  end
end

app/helpers/client_legal_forms_helper.rb
module ClientLegalFormsHelper
end

app/views/client_legal_forms/_client_legal_form.html.erb
<div id="<%= dom_id client_legal_form %>">
  <p>
    <strong>Client:</strong>
    <%= client_legal_form.client.last_name %>, <%= client_legal_form.client.first_name %>
  </p>

  <div class="w-3/5 bg-slate-300 text-slate-700 border border-slate-300 border-solid py-2 pl-2"><strong>Legal form:</strong> <%= client_legal_form.legal_form.name %></div>
  <div class="w-3/5 grid grid-cols-2 border border-slate-300 border-solid">
  <% bg_color = 'bg-slate-200' %>
  <% @answers.each.with_index do |answer, index| %>
    <% bg_color = index.even? ? "bg-slate-50" : "bg-slate-200"  %>
      <%  if answer.question_type == "SubForm"  %>
        <div class="py-2 pl-2 <%=bg_color %>"><%=answer.position %>) <%=answer.question%></div>
        <div class="py-2 pr-2"></div>
          <% subforms = answer.get_subform %>
          <%subforms.each do |subform| %>
            <% subform.client_answers.each do |answer| %>
              <div class="py-2 pl-2 <%=bg_color %>"><%=answer.question %></div>
              <div class="py-2 pr-2 <%=bg_color %>"><%=answer.answer || '<span class="text-red-700">No Answer</span>'.html_safe() %></div>
            <% end %>
          <% end %>
        </div>
      <% else %>
        <div class="py-2 pl-2 <%=bg_color %>"><%=answer.position %>) <%=answer.question %></div>
        <div class="py-2 pr-2 <%=bg_color %>"><%=answer.answer || '<span class="text-red-700">No Answer</span>'.html_safe() %></div>
      <% end %>
  <% end %>
  </div>
  <%= link_to "Download CSV", download_csv_client_legal_forms_path(format: :csv, formID: @client_legal_form_id), class: 'bg-blue-950 text-white text-lg inline p-2'%>

  <p>
    <strong>First login date:</strong>
    <%= client_legal_form.first_login_date %>
  </p>

  <p>
    <strong>Most recent login:</strong>
    <%= client_legal_form.most_recent_login %>
  </p>

</div>

app/views/client_legal_forms/_client_legal_form_grid.html.erb
<div id="client_legal_forms" class="grid grid-cols-3 w-3/5 border border-slate-300 border-solid">
  <div class="font-bold">Client Name</div>
  <div class="font-bold">Form Type</div>
  <div></div>
  <% bg_color = "bg-slate-100" %>
  <% @client_legal_forms.each.with_index do |client_legal_form, index| %>
    <% bg_color = index.even? ? "bg-slate-50" : "bg-slate-200"  %>
    <div class="py-2 pl-2 <%=bg_color%>"><%=client_legal_form.client.last_name %>,  <%=client_legal_form.client.first_name %> <%=client_legal_form.client.middle_name %></div>
    <div class="py-2 <%=bg_color%>"><%=client_legal_form.legal_form.name %></div>
    <div class="py-2 pr-2 <%=bg_color%>">
      <% if client_legal_form.first_login_date != nil %>
        <%= link_to "View Form", client_legal_form %> |
        <%= link_to "Export CSV", download_csv_client_legal_forms_path(format: :csv, formID: client_legal_form.id) %>
      <% else %>
        Client has not logged in yet.
      <% end %>
    </div>
  <% end %>
</div>

app/views/client_legal_forms/_client_legal_form_input.html.erb
<%=testVar %>
<div id="<%= dom_id client_legal_form %>">
  <h1>This will be the user form.  Don't confuse with the amdin section </h1>
  <p>
    <strong>Client:</strong>
    <%= client_legal_form.client.last_name %>, <%= client_legal_form.client.first_name %>
  </p>

<%= form_with model: @client_data_entries do |f| %>
  <div class="w-3/5 bg-slate-300 text-slate-700 border border-slate-300 border-solid py-2 pl-2"><strong>Legal form:</strong> <%= client_legal_form.legal_form.name %></div>
  <div class="w-3/5 grid grid-cols-2 border border-slate-300 border-solid">
  <% bg_color = 'bg-slate-200' %>
  <%= f.fields_for :client_answers do |client_answer_form| %>
    <% bg_color = "bg-slate-50"# f.options[:child_index].even? ? "bg-slate-50" : "bg-slate-200"  %>
    <div class="py-2 pl-2 <%=bg_color %>"><%=client_answer_form.object.position %>) <%=client_answer_form.object.question %></div>
    <div class="py-2 pr-2 <%=bg_color %>"><%= client_answer_form.text_field :answer %></div>
  <% end %>
  </div>
    <%= f.submit %>
<% end  %>
</div>

app/views/client_legal_forms/_form.html.erb
<%= form_with(model: client_legal_form) do |form| %>
  <% if client_legal_form.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client_legal_form.errors.count, "error") %> prohibited this client_legal_form from being saved:</h2>

      <ul>
        <% client_legal_form.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :client_id, style: "display: block" %>
    <% if @client_dropdown %>
      <%= form.select :client_id, @client_dropdown.unshift(['--Select a Client--', 0]) %>
    <% end %>
    <% if @client %>
      <div class="py-2"><%=@client.last_name %>, <%=@client.first_name %> <%=@client.middle_name %></div>
      <%= form.hidden_field :client_id, value: @client.id %>
    <% end %>
  </div>

  <div>
    <%= form.label :legal_form_id, style: "display: block" %>
    <%= form.select :legal_form_id, @legal_form_dropdown.unshift(['--Select a Form--', 0]) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/client_legal_forms/edit.html.erb
<h1>Editing client legal form</h1>

<%= render "form", client_legal_form: @client_legal_form %>

<br>

<div>
  <%= link_to "Show this client legal form", @client_legal_form %> |
  <%= link_to "Back to client legal forms", client_legal_forms_path %>
</div>

app/views/client_legal_forms/forms_by_client.html.erb
<p style="color: green"><%= notice %></p>

<h1>Client legal forms</h1>

<%= render "client_legal_form_grid", client_legal_forms: @client_legal_forms %>


<%= link_to "New client legal form", new_client_legal_form_path %>

app/views/client_legal_forms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Client legal forms</h1>


<div id="client_legal_forms" class="grid grid-cols-3 w-3/5 border border-slate-300 border-solid">
  <div class="font-bold">Client Name</div>
  <div class="font-bold">Form Type</div>
  <div></div>
  <% bg_color = "bg-slate-100" %>
  <% @client_legal_forms.each.with_index do |client_legal_form, index| %>
    <% bg_color = index.even? ? "bg-slate-50" : "bg-slate-200"  %>
    <div class="py-2 pl-2 <%=bg_color%>"><%=client_legal_form.client.last_name %>,  <%=client_legal_form.client.first_name %></div>
    <div class="py-2 <%=bg_color%>"><%=client_legal_form.legal_form.name %></div>
    <div class="py-2 pr-2 <%=bg_color%>">
      <%= link_to "View Form", client_legal_form %> |
      <%= link_to "Export CSV", download_csv_client_legal_forms_path(format: :csv, formID: client_legal_form.id) %>
    </div>
<% end %>
</div>

<%= link_to "New client legal form", new_client_legal_form_path %>

app/views/client_legal_forms/new.html.erb
<h1>New client legal form</h1>

<%= render "form", client_legal_form: @client_legal_form %>

<br>

<div>
  <%= link_to "Back to client legal forms", client_legal_forms_path %>
</div>

app/views/client_legal_forms/new_for_client.html.erb
<p style="color: green"><%= notice %></p>

<h1>Client legal forms</h1>

<%= render "form", client_legal_form: @client_legal_form %>


<%= link_to "New client legal form", new_client_legal_form_path %>

app/views/client_legal_forms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @client_legal_form %>

<div>
  <%= link_to "Edit this client legal form", edit_client_legal_form_path(@client_legal_form) %> |
  <%= link_to "Back to client legal forms", client_legal_forms_path %>

  <%= button_to "Destroy this client legal form", @client_legal_form, method: :delete %>
</div>

app/views/client_legal_forms/userEdit.html.erb
<p style="color: green"><%= notice %></p>
<%= render "client_legal_form_input", client_legal_form: @client_legal_form_input %>