config/routes.rb
Rails.application.routes.draw do
  resources :client_data_entries do
    member do
      get 'sub_form', to: "client_data_entries#sub_form"
    end
    member do
      get 'sub_form_list', to: "client_data_entries#sub_form_list"
    end
  end
  resources :client_legal_forms do
    collection do
      get :download_csv
    end
    member do
      get '/new_for_client/', to: "client_legal_forms#new_for_client"
    end
    member do
      get '/forms_by_client/', to: "client_legal_forms#forms_by_client"
    end
  end
  get '/subForm/:id', to: 'client_data_entries#subForm'
  get '/myForm/:id', to: 'client_legal_forms#userEdit'
  get '/hashError', to: 'home#bad_hash'
  get '/clientSuccess', to: 'home#client_success'
  get '/downloadCsv/:id', to: 'client_answers#download_csv'
  resources :clients
  resources :legal_form_questions
  resources :legal_forms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :client_legal_forms, dependent: :destroy
end

app/controllers/clients_controller.rb
require 'csv'

class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to clients_path, notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      puts "client params"
      puts client_params
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy!

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:first_name, :last_name, :middle_name)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <p>
    <strong>First name:</strong>
    <%= client.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= client.last_name %>
  </p>

  <p>
    <strong>Middle name:</strong>
    <%= client.middle_name %>
  </p>

</div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :middle_name, style: "display: block" %>
    <%= form.text_field :middle_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Add Form", new_for_client_client_legal_form_path(@client.id) %>
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Clients</h1>

<div id="client_legal_forms" class="grid grid-cols-2 w-3/5 border border-slate-300 border-solid">
  <div class="font-bold">Name</div>
  <div></div>
  <% bg_color = "bg-slate-100" %>
  <% @clients.each.with_index do |client, index| %>
    <% bg_color = index.even? ? "bg-slate-50" : "bg-slate-200"  %>
    <div class="py-2 pl-2 <%=bg_color%>"><%=client.last_name %>, <%=client.first_name %> <%=client.middle_name %></div>
    <div class="py-2 pr-2 <%=bg_color%>">
      <%= link_to "Edit this client", edit_client_path(client.id) %> |
      <%= link_to "View Clients Forms", forms_by_client_client_legal_form_path(client.id) %> |
      <%= link_to "Add Form", new_for_client_client_legal_form_path(client.id) %>
    </div>
  <% end %>
</div>

<%= link_to "New client", new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @client %>

<div>
  <%= link_to "Edit this client", edit_client_path(@client) %> |
  <%= link_to "Back to clients", clients_path %>

  <%= button_to "Destroy this client", @client, method: :delete %>
</div>