config/routes.rb
Rails.application.routes.draw do
  resources :client_data_entries do
    member do
      get 'sub_form', to: "client_data_entries#sub_form"
    end
    member do
      get 'sub_form_list', to: "client_data_entries#sub_form_list"
    end
  end
  resources :client_legal_forms do
    collection do
      get :download_csv
    end
    member do
      get '/new_for_client/', to: "client_legal_forms#new_for_client"
    end
    member do
      get '/forms_by_client/', to: "client_legal_forms#forms_by_client"
    end
  end
  get '/subForm/:id', to: 'client_data_entries#subForm'
  get '/myForm/:id', to: 'client_legal_forms#userEdit'
  get '/hashError', to: 'home#bad_hash'
  get '/clientSuccess', to: 'home#client_success'
  get '/downloadCsv/:id', to: 'client_answers#download_csv'
  resources :clients
  resources :legal_form_questions
  resources :legal_forms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/legal_form_question.rb
class LegalFormQuestion < ApplicationRecord
  belongs_to :legal_form
  has_many :client_answers
end

app/controllers/legal_form_questions_controller.rb
class LegalFormQuestionsController < ApplicationController
  before_action :set_legal_form_question, only: %i[ show edit update destroy ]

  # GET /legal_form_questions or /legal_form_questions.json
  def index
    @legal_form_questions = LegalFormQuestion.all
  end

  # GET /legal_form_questions/1 or /legal_form_questions/1.json
  def show
  end

  # GET /legal_form_questions/new
  def new
    @legal_form_question = LegalFormQuestion.new
    @legal_form_dropdown = LegalForm.all.map { |legal_form| [legal_form.name, legal_form.id] }
  end

  # GET /legal_form_questions/1/edit
  def edit
  end

  # POST /legal_form_questions or /legal_form_questions.json
  def create
    @legal_form_question = LegalFormQuestion.new(legal_form_question_params)

    respond_to do |format|
      if @legal_form_question.save
        format.html { redirect_to legal_form_question_url(@legal_form_question), notice: "Legal form question was successfully created." }
        format.json { render :show, status: :created, location: @legal_form_question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @legal_form_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /legal_form_questions/1 or /legal_form_questions/1.json
  def update
    respond_to do |format|
      if @legal_form_question.update(legal_form_question_params)
        format.html { redirect_to legal_form_question_url(@legal_form_question), notice: "Legal form question was successfully updated." }
        format.json { render :show, status: :ok, location: @legal_form_question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @legal_form_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /legal_form_questions/1 or /legal_form_questions/1.json
  def destroy
    @legal_form_question.destroy!

    respond_to do |format|
      format.html { redirect_to legal_form_questions_url, notice: "Legal form question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_legal_form_question
      @legal_form_question = LegalFormQuestion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def legal_form_question_params
      params.require(:legal_form_question).permit(:question, :question_type, :position, :options, :legal_form_id)
    end
end

app/helpers/legal_form_questions_helper.rb
module LegalFormQuestionsHelper
end

app/views/legal_form_questions/_form.html.erb
<%= form_with(model: legal_form_question) do |form| %>
  <% if legal_form_question.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(legal_form_question.errors.count, "error") %> prohibited this legal_form_question from being saved:</h2>

      <ul>
        <% legal_form_question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :legal_form_id, style: "display: block" %>
    <%= form.select :legal_form_id, @legal_form_dropdown.unshift(['--Select a Form--', 0]) %>
  </div>

  <div>
    <%= form.label :question, style: "display: block" %>
    <%= form.text_field :question %>
  </div>

  <div>
    <%= form.label :position, style: "display: block" %>
    <%= form.number_field :position %>
  </div>

  <div>
    <%= form.label :question_type, style: "display: block" %>
    <%= form.select :question_type, ['Text', 'Dropdown', 'Checkbox']%>
  </div>

  <div>
    <%= form.label :options, style: "display: block" %>
    <%= form.text_field :options %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/legal_form_questions/_legal_form_question.html.erb
<div id="<%= dom_id legal_form_question %>" class="text-red-400">
  <p>
    <strong>Question:</strong>
    <%= legal_form_question.question %>
  </p>

  <p>
    <strong>Position:</strong>
    <%= legal_form_question.position %>
  </p>

  <p>
    <strong>Question Type:</strong>
    <%= legal_form_question.question_type %>
  </p>

  <p>
    <strong>Options:</strong>
    <%= legal_form_question.options %>
  </p>

  <p>
    <strong>Legal form:</strong>
    <%= legal_form_question.legal_form_id %>
  </p>

</div>

app/views/legal_form_questions/_legal_form_question_row.html.erb
<div id="<%= dom_id legal_form_question %>" class="text-red-">
  <div style="width: 30%">
    <strong>Question:</strong>
    <%= legal_form_question.question %>
  </div>

  <p>
    <strong>Position:</strong>
    <%= legal_form_question.position %>
  </p>

  <p>
    <strong>Question Type:</strong>
    <%= legal_form_question.question_type %>
  </p>

  <p>
    <strong>Options:</strong>
    <%= legal_form_question.options %>
  </p>

  <p>
    <strong>Legal form:</strong>
    <%= legal_form_question.legal_form_id %>
  </p>

</div>

app/views/legal_form_questions/edit.html.erb
<h1>Editing legal form question</h1>

<%= render "form", legal_form_question: @legal_form_question %>

<br>

<div>
  <%= link_to "Show this legal form question", @legal_form_question %> |
  <%= link_to "Back to legal form questions", legal_form_questions_path %>
</div>

app/views/legal_form_questions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Legal form questions</h1>

<div id="legal_form_questions">
  <% @legal_form_questions.each do |legal_form_question| %>
    <%= render legal_form_question %>
    <p>
      <%= link_to "Show this legal form question", legal_form_question %>
    </p>
  <% end %>
</div>

<%= link_to "New legal form question", new_legal_form_question_path %>

app/views/legal_form_questions/new.html.erb
<h1>New legal form question</h1>

<%= render "form", legal_form_question: @legal_form_question %>

<br>

<div>
  <%= link_to "Back to legal form questions", legal_form_questions_path %>
</div>

app/views/legal_form_questions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @legal_form_question %>

<div>
  <%= link_to "Edit this legal form question", edit_legal_form_question_path(@legal_form_question) %> |
  <%= link_to "Back to legal form questions", legal_form_questions_path %>

  <%= button_to "Destroy this legal form question", @legal_form_question, method: :delete %>
</div>